### ISSUE TITLE
Need clarification of param_range

### ISSUE THREAD

**Issue by zdcrandall** [lightingghost/chemopt#2]
Will you explain the purpose of the param_range variable in realreaction.py? Is the param_range variable indicating the minimum and maximum value of each parameter? For example, 'voltage' has a desired range of 0.0 to 5.0, so param_range has the tuple (0.0, 5.0).

I am asking because when I try to run realreaction.py, it usually ends up suggesting parameter values outside of the parameter range given, so I believe I am misunderstanding something. To help with reproducibility, I trained the network on 2000 epochs without changing any other parameters in the config.json. I have also tried 200 epochs with a evaluation period of 50, changing nothing else. Each time, if I entered a reaction yield of 10 it would produce negative voltage and flow rate values.

**Comment by lightingghost** [comment]
Yes. param_range indicates the range of each parameter.

I think the problem comes from the yield you inputed: Note that the output range of the functions at training time is normalized to [0, 1], therefore the reaction yield you entered should be also in this range. (In real life reaction yield is in the range of [0, 1] as well.)

However, in my own experience, even if each reaction yield I entered lies in the range of [0, 1], in rare cases the algorithm will give out-of-range suggestions. What I typically do is to truncate the suggestion to the desired range. (eg, set it to be 0.0 if less than 0.)

**Comment by zdcrandall** [comment]
Ahhh that makes sense. I was thinking of it in terms of "percent yield" when I was inputting yield. Thank you for the clarification!
